version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db-metronom-1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'metronom-dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mypassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mypassword'
    ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '6603:3306'
    expose:
    # Opens port 3306 on the container
    - '6603'
    # Where our data will be persisted
    command: --init-file /data/application/init.sql
    volumes:
    - ./init.sql:/data/application/init.sql
    - db:/var/lib/mysql
    networks:
    - metronom-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-metronom-1.0
    links:
    - db
    depends_on:
    - db
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
    - metronom-network

#    command: --init-file /data/application/start-server.sh
#    volumes:
#    - ./start-server.sh:/data/application/start-server.sh

networks:
  metronom-network:
    driver: bridge

volumes:
  db: {}
